[platformio]
default_envs = esp32_eth_dev

[env:esp32_eth_dev]
platform = espressif32
framework = arduino
board = wt32-eth01
monitor_speed = 115200
build_flags =
  -I include
lib_ldf_mode = deep+
lib_deps =
  bblanchon/ArduinoJson

